"""initial tables

Revision ID: 5e3ccd5559e5
Revises: 
Create Date: 2025-06-04 19:07:31.511380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e3ccd5559e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_number', sa.String(length=20), nullable=False),
    sa.Column('size', sa.String(length=10), nullable=False),
    sa.Column('tare', sa.Integer(), nullable=True),
    sa.Column('terminal', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('available_to', sa.Date(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('release_reference', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('booked_date', sa.DateTime(), nullable=True),
    sa.Column('container_number', sa.String(length=20), nullable=False),
    sa.Column('release_reference', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=10), nullable=True),
    sa.Column('tare', sa.Integer(), nullable=True),
    sa.Column('terminal', sa.String(length=50), nullable=True),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('available_to', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('damaged', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('containers')
    op.drop_table('user')
    # ### end Alembic commands ###
